"""empty message

Revision ID: 48fef9a2ddbb
Revises: 
Create Date: 2024-08-06 16:56:34.637009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fef9a2ddbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_config', sa.Column('guild_id', sa.Integer(), nullable=False))
    op.add_column('guild_config', sa.Column('config_type', sa.String(), nullable=False))
    op.add_column('guild_config', sa.Column('config_id', sa.Integer(), nullable=False))
    op.drop_column('guild_config', 'log_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_config', sa.Column('log_channel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('guild_config', 'config_id')
    op.drop_column('guild_config', 'config_type')
    op.drop_column('guild_config', 'guild_id')
    # ### end Alembic commands ###
