"""empty message

Revision ID: 2051098ba061
Revises: 857e30aea903
Create Date: 2024-10-21 21:11:05.082679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2051098ba061"
down_revision: Union[str, None] = "857e30aea903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guild_config")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_config",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("config_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("config_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="guild_config_pkey"),
    )
    # ### end Alembic commands ###
