"""empty message

Revision ID: 75e10d2dafed
Revises: 2051098ba061
Create Date: 2024-10-21 21:28:23.169963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e10d2dafed'
down_revision: Union[str, None] = '2051098ba061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_config', 'message',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_config', 'message',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
